[description]

== Description

****
ChecklistBank is a platform that supports the publication, analysis, and curation of checklists with emphasis in taxonomic and nomenclatural data. It is an integral part of the infrastructure developed and maintained by the Catalogue of Life (COL) and the Global Biodiversity Information Facility (GBIF). 

A detailed tutorial of the general tools of ChecklistBank can be found https://doi.org/10.35035/ce-9sw4-e095[here].  

In addition to the general tools, users can create and publish new datasets through ChecklistBank in two different ways:

* Project: datasets constructed and managed within ChecklistBank
* External: datasets created outside ChecklistBank and imported as FAIR data resources into the platform.

Both of them benefit from many common features that ChecklistBank delivers as an open data infrastructure: standards compliance, validation and reporting, multiple download options, rich API support, etc.

ChecklistBank users can use the *Project functionality* to create new Checklists from existing datasets hosted in the platform (also referred here as sources), combining their data totally or partially. For example to create a national checklist, based on taxonomic checklists and articles from a specific country. 

This tutorial describes the functions available for assembling a checklist and delivering it as a dataset. These tools are already in use to construct the Catalogue of life data product.

*Project functionality* includes the following features: 

* Interactive assembly process.
* Include total or partial information from any other datasets in ChecklistBank.
* Select or block specific parts from a any given dataset included in the project.
* Synchronisation between the main project and the source dataset.
* Stable static versions called releases, with stable record identifiers. 


****

=== Audience
This tutorial is for Biodiversity information systems, taxonomists, governmental entities, online platforms, and any other people or institutions interested in assembling a checklist from preexisting  lists in ChecklistBank.


